<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'debug' => 'get5bd8d8e22c050186261564',
  'project.cache' => 'get5bd8d8e22c070770704047',
  'project.src' => 'get5bd8d8e22c083875179461',
  'project.root' => 'get5bd8d8e22c095642122681',
  'project.namespace' => 'get5bd8d8e22c0a2527089192',
  'error.handler' => 'get5bd8d8e22c0ab835033125',
  'response.emitter' => 'get5bd8d8e22e918766821123',
  'Sherpa\\App\\App' => 'get5bd8d8e2302ad828517341',
  'base_path' => 'get5bd8d8e2302bc539498831',
);

    protected function get5bd8d8e22c050186261564()
    {
        return true;
    }

    protected function get5bd8d8e22c070770704047()
    {
        return \DI\Definition\StringDefinition::resolveExpression('project.cache', '{project.root}/var/cache', $this->delegateContainer);
    }

    protected function get5bd8d8e22c083875179461()
    {
        return \DI\Definition\StringDefinition::resolveExpression('project.src', '{project.root}/src', $this->delegateContainer);
    }

    protected function get5bd8d8e22c095642122681()
    {
        return '/var/www/html/sherpa-framework/tests';
    }

    protected function get5bd8d8e22c0a2527089192()
    {
        return 'App\\';
    }

    protected function get5bd8d8e22c0ab835033125()
    {
        return $this->resolveFactory(static function () {
    return new \Middlewares\ErrorHandlerDefault();
}, 'error.handler');
    }

    protected function get5bd8d8e22e918766821123()
    {
        return $this->resolveFactory(static function () {
    return new \Zend\Diactoros\Response\SapiEmitter();
}, 'response.emitter');
    }

    protected function get5bd8d8e2302ad828517341()
    {
        return $this->delegateContainer->get('Sherpa\\App\\App');
    }

    protected function get5bd8d8e2302bc539498831()
    {
        return '/sherpa-framework/tests/_public';
    }

}
